import org.apache.tools.ant.filters.ReplaceTokens

plugins {
    id 'java'
    id 'com.gradleup.shadow' version '9.5.1'
}

group = pluginGroup
version = pluginVersion

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
    maven { url = 'https://hub.spigotmc.org/nexus/content/groups/public/' }
    maven { url = 'https://oss.sonatype.org/content/groups/public/' }
    maven { url = 'https://repo.aikar.co/content/groups/aikar/' }
    maven { url = 'https://jitpack.io' }
    maven { url = 'https://repo.codemc.io/repository/maven-public/' }
    maven { url = 'https://libraries.minecraft.net/' }
}

dependencies {
    implementation 'co.aikar:acf-core:0.5.1-SNAPSHOT'
    implementation 'co.aikar:acf-paper:0.5.1-SNAPSHOT'
    implementation 'de.tr7zw:item-nbt-api:2.15.7'
    implementation 'com.github.cryptomorin:XSeries:13.7.1'

    compileOnly 'org.spigotmc:spigot-api:1.21.4-R0.1-SNAPSHOT'
    compileOnly 'com.mojang:authlib:6.0.54'

    compileOnly 'org.projectlombok:lombok:1.18.42'
    annotationProcessor 'org.projectlombok:lombok:1.18.42'
}

shadowJar {
    archiveClassifier = ''
    relocate 'co.aikar.commands', 'net.splodgebox.monthlycrates.acf'
    relocate 'co.aikar.locales', 'net.splodgebox.monthlycrates.acf.locales'
    relocate 'com.cryptomorin.xseries', 'net.splodgebox.monthlycrates.utils.xseries'
    relocate 'de.tr7zw.changeme.nbtapi', 'net.splodgebox.monthlycrates.utils.nbtapi'
}

processResources {
    duplicatesStrategy = 'exclude'
    filesMatching('**/plugin.yml') {
        filter ReplaceTokens, tokens: [version: version.toString()]
    }
}

tasks.named('build').configure {
    dependsOn shadowJar
}